### ISSUE TITLE
Add new messages to the bottom

### ISSUE THREAD

**Issue by byheaven** [LelouchHe/logseq-local-telegram-bot#10]
Hi, it's me again😝. Can you please add an option of inverting the order so the new messages will be added to the bottom rather than the top? Thank you!

**Comment by LelouchHe** [comment]
I have released a new version v0.2.2, which includes an option "appendAtBottom". Try that to see whether it fixes this issue

**Comment by byheaven** [comment]
Works perfectly. Thank you!
