### ISSUE TITLE
Feature Request: add timestamp to each message

### ISSUE THREAD

**Issue by FelixHuoEZ** [LelouchHe/logseq-local-telegram-bot#15]
Feature Request: add timestamp to each message, like [shady2k](https://github.com/shady2k)/[logseq-inbox-telegram-plugin](https://github.com/shady2k/logseq-inbox-telegram-plugin)

**Comment by LelouchHe** [comment]
Thanks for trying this plugin.

I have released a new version (v0.2.9 and up) with a new option "Add Timestamp", when enabled ,it will add "HH:mm" to the front of the received text/photo

Could you help give it a try to see whether it's ok?

Thanks

**Comment by LelouchHe** [comment]
Close it for now . Feel free to raise any new issue ! Thanks

**Comment by FelixHuoEZ** [comment]
It works, thanks
