### ISSUE TITLE
Contents behind # are displayed incorrectly in Logseq.

### ISSUE THREAD

**Issue by byheaven** [LelouchHe/logseq-local-telegram-bot#18]
If I send "#tag text123" to Logseq, it will only shows "#tag". 
"text123 #tag text456" => "text123 #tag"

So I think the contents behind the # is missing when creating blocks in Logseq.

**Comment by LelouchHe** [comment]
it's a bug introduced when i tried to handle markdown message from telegram.

the latest release should fix it.

thanks for pointing out this bug

**Comment by FelixHuoEZ** [comment]
> it's a bug introduced when i tried to handle markdown message from telegram.
> 
> the latest release should fix it.
> 
> thanks for pointing out this bug

0.2.13 works, thanks.
