### ISSUE TITLE
Feature request: get image type Files from Telegram, to get a original size image

### ISSUE THREAD

**Issue by FelixHuoEZ** [LelouchHe/logseq-local-telegram-bot#21]
When I share an image on Telegram, it gets compressed. 
I want to share the original size image instead. 
To do this, I tried sending the image file directly to Telegram using the "File" option instead of the "Photo" option. 
Unfortunately, the plugin did not recognize it. 

It would be greatly appreciated if the plugin could support this feature.

**Comment by LelouchHe** [comment]
sure, let me investigate their File api first.

but one thing from Logseq is: there is no way to actually download the file directly (without a special permission request, which won't be available all the time), so if this image file can't be recognized as an image, we might not be able to handle it.

anyway, i will let you know my investigation soon.

**Comment by LelouchHe** [comment]
It seems that images sent as file can be recognized as images.

Could you try the latest release (0.2.14) to see whether it resolve this issue?

Thanks

**Comment by LelouchHe** [comment]
close it for now. feel free to raise any issue later
