### ISSUE TITLE
Use markdown to render received photo

### ISSUE THREAD

**Issue by LelouchHe** [LelouchHe/logseq-local-telegram-bot#4]
For now, it uses "renderer" command with img tag to render received photo, which doesn't work well on mobile platforms.

Hope it could change to markdown format, like `![caption](photoUrl)`

A feature request form [byheaven](https://github.com/byheaven)

**Comment by LelouchHe** [comment]
I assume that you mean to send photo to Telegram?

I'm still working on that feature, for now all data sent is plain text. This feature would be together with embed blocks (for now, it just sends something like "((xxx-yyy-zzz))"), since they both might need some parsing on this plain text to be properly generated and sent

**Comment by LelouchHe** [comment]
Hi [byheaven](https://github.com/byheaven),

Do you mean on mobile Logseq? I'm afraid that the photo received can't be directly displayed as url, since Telegram file url generally expire in 1 day. I used "renderer" to get the latest url from its permanent file id to make sure the url is always valid.

So currently, there might not be a good way to walk around this problem.

BTW, if you have mobile Logseq installed, do you still prefer to use Telegram? Is it possible to copy/paste the photo directly there, like on desktop? I'm asking this because I don't have an eligible mobie device to try Logseq app, and that's part of the reasons I'm creating this plugin, since Telegram doesn't require the latest iOS version.

**Comment by byheaven** [comment]
https://github.com/LelouchHe/logseq-local-telegram-bot/issues/3#issuecomment-1433976457

**Comment by LelouchHe** [comment]
See https://github.com/LelouchHe/logseq-local-telegram-bot/pull/6 

it's a possible fix for this issue.

**Comment by byheaven** [comment]
Just viewed the pr and that's really impressive! Looking forward to test it!
Regarding the local saving feature, I think the only functionality I need is for the plugin to provide a slash command or right-click option that allows me to transfer the photo and save it locally. It's okay if this feature is only available on desktop. For important images, the safest and most long-lasting way to keep them is by saving them locally.

**Comment by LelouchHe** [comment]
I have released the v0.0.9 with this fix. 

Could you help give it a try to see whether it fixes the mobile photo render issue?

Thanks

**Comment by byheaven** [comment]
Yes it works like a charm on my iPad! Let's see if it can automatically update the url after several days.

**Comment by LelouchHe** [comment]
close it for now. feel free to create a new one when running into anything new!
